version: '3.8'
services:
  frontend:
    container_name: mern_frontend
    build: frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    container_name: mern_backend
    build: backend/helloService/
    ports:
      - "3001:3001"

  
  profileservice:
    container_name: mern_profileservice
    build: backend/profileservice/
    ports:
      - "3002:3002"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false